title: ZKWeng
author: Zhengyang Kris Weng
email: wengmister@gmail.com
description: >- 
  Welcome! This is ZKW's project portfolio page.
baseurl: "/zkweng.github.io" # change if your repo name is different
url: "https://wengmister.github.io" # use your actual GitHub Pages URL
github_username: zkweng

# Build settings
theme: minima
plugins:
  - jekyll-feed

# File structure settings
image_path: /assets/images

# Build settings
markdown: kramdown
permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name

sass:
  sass_dir: _sass
  style: compressed
